apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.back_svc.name }}
spec:
  type: {{ .Values.back_svc.type }}
  selector:
    app: {{ .Values.backend.name }}
  ports:
    - port: {{ .Values.back_svc.port }}
      targetPort: {{ .Values.back_svc.targetPort }}
      nodePort: {{ .Values.back_svc.nodePort }}
      name: http