apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.db_svc.name }}
spec:
  type: {{ .Values.db_svc.type }}
  selector:
    app: {{ .Values.db.name }}
  ports:
    - port: {{ .Values.db_svc.port }}
      targetPort: {{ .Values.db_svc.targetPort }}
      name: {{ .Values.db.name }}