apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.front_svc.name }}
spec:
  type: {{ .Values.front_svc.type }}
  selector:
    app: {{ .Values.frontend.name }}
  ports:
    - port: {{ .Values.front_svc.port }}
      targetPort: {{ .Values.front_svc.targetPort }}
      name: {{ .Values.front_svc.name }}
      nodePort: {{ .Values.front_svc.nodePort }}