apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: patient-tracking-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/turangozukara/patient-tracking-platform-argocd
    targetRevision: main
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: patient-tracking
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
  revisionHistoryLimit: 10