apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.backend.name }}
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.backend.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.backend.name }}
      annotations:
        co.elastic.logs/enabled: "true"
    spec:
      nodeSelector:
        {{ toYaml .Values.nodeSelector | nindent 8 }}
      initContainers:
        - name: wait-for-db
          image: busybox
          command: ['sh', '-c', 'until nc -z postgres-svc 5432; do echo waiting for db; sleep 2; done;']
      containers:
        - name: {{ .Values.backend.name }}
          image: {{ .Values.backend.image }}
          envFrom:
            - secretRef:
                name: backend-secrets
          ports:
            - containerPort: 80