apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.frontend.name }}
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.frontend.name }}
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "15090"
        prometheus.io/path: /metrics
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
      labels:
        app: {{ .Values.frontend.name }}
    spec:
      nodeSelector:
        {{ toYaml .Values.nodeSelector | nindent 8 }}
      containers:
        - name: {{ .Values.frontend.name }}
          image: {{ .Values.frontend.image }}
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.frontend.containerPort }}