apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
type: {{ .Values.secrets.type }}
stringData:
  ConnectionStrings__DefaultConnection: {{ .Values.secrets.ConnectionStrings__DefaultConnection }}
  JwtSettings__Secret: "{{ .Values.secrets.JwtSettings__Secret }}"
  JwtSettings__ExpiryDays: "{{ .Values.secrets.JwtSettings__ExpiryDays }}"
  JwtSettings__Issuer: "{{ .Values.secrets.JwtSettings__Issuer }}"
  JwtSettings__Audience: "{{ .Values.secrets.JwtSettings__Audience }}"
  POSTGRES_DB: "{{ .Values.secrets.POSTGRES_DB }}"
  POSTGRES_USER: "{{ .Values.secrets.POSTGRES_USER }}"
  POSTGRES_PASSWORD: "{{ .Values.secrets.POSTGRES_PASSWORD }}"